name: Build Android App

on:
  push:
    branches:
      - main
    paths:
      - 'android-app/*.py'
      - 'android-app/*.kv'
      - 'android-app/*.spec'
      - 'android-app/*.png'
      - '.github/workflows/build-android.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install dependencies
      run: |
        sudo apt update
        pip install cython
        pip install kivy
        pip install kivymd
        pip install buildozer

    - name: Run buildozer
      run: |
        cd android-app/
        buildozer android debug

    - name: Prepare artifact
      id: prepareArtifact
      run: |
        artifactUpload=`ls -t android-app/bin/*.apk | head -n1` && echo "artifactUpload=$artifactUpload" >> $GITHUB_OUTPUT
      
    - name: Get last commit tag
      id: lastTag
      run: |
        artifactName=`git describe --tags --abbrev=0` && echo "artifactName=$artifactName" >> $GITHUB_OUTPUT
    
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.lastTag.outputs.artifactName }}
        path: ${{ steps.prepareArtifact.outputs.artifactUpload }}
    
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add android-app/bin/*
        git commit -m "Add generated APK from workflows" -a
        git push