name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install python3-pip
        sudo apt install openjdk-17-jdk
        pip install cython
        pip install kivy
        pip install kivymd
        pip install buildozer

    - name: Run buildozer
      run: |
        cd android-app/
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: android-app/bin/*.apk